#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot $PICTURE"

BLUR="-filter Gaussian -resize 10% -define filter:sigma=2.5 -resize 1000%"

$SCREENSHOT
convert $PICTURE $BLUR $PICTURE
i3lock -i $PICTURE
rm $PICTURE
