#!/usr/bin/env bash

# Video lock
# env XSECURELOCK_SAVER=saver_mplayer XSECURELOCK_DISCARD_FIRST_KEYPRESS=0 xsecurelock

# XScreensaver
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_XSCREENSAVER_PATH=/usr/libexec/xscreensaver
export XSECURELOCK_SAVER=saver_xscreensaver 
env xsecurelock
